Cicd integretion test 10

diff --git a/.github/workflows/appium-android-ci.yml b/.github/workflows/appium-android-ci.yml
--- a/.github/workflows/appium-android-ci.yml
+++ b/.github/workflows/appium-android-ci.yml
@@ -49,7 +49,12 @@ jobs:
       - name: Start Appium Server
         run: |
           appium --base-path /wd/hub --log appium_server.log &
-
+          sleep 10
+            if ! nc -z localhost 4723; then
+              echo "❌ Appium server failed to start!"
+              exit 1
+            fi
+            echo "✅ Appium server is running!"
   run-tests:
     needs: setup-environment
     runs-on: ubuntu-latest
