Cicd integretion test 35

diff --git a/.github/workflows/appium-android-ci.yml b/.github/workflows/appium-android-ci.yml
--- a/.github/workflows/appium-android-ci.yml
+++ b/.github/workflows/appium-android-ci.yml
@@ -184,11 +184,20 @@ jobs:
           npm install -g appium@latest
           appium driver install uiautomator2
           
-           # Ensure correct Appium path is used
-            echo "Setting Appium Path..."
-            echo "export APPIUM_PATH=/opt/hostedtoolcache/node/20.18.2/x64/lib/node_modules/appium/build/lib/main.js" >> $GITHUB_ENV
-            echo "Appium Main.js Path: $APPIUM_PATH"
-          
+           # Find correct Appium path
+          export APPIUM_PATH=$(npm root -g)/appium/build/lib/main.js
+          echo "Setting Appium Path..."
+          echo "export APPIUM_PATH=$APPIUM_PATH" >> $GITHUB_ENV
+          echo "Appium Main.js Path: $APPIUM_PATH"
+
+          # Verify if Appium main.js exists
+          if [ -f "$APPIUM_PATH" ]; then
+            echo "✅ Appium main.js found!"
+          else
+            echo "❌ Appium main.js is missing! Check installation."
+            exit 1
+          fi
+
           appium -v
           which appium
 #          echo "Appium Root Path: $(npm root -g)"
